### ISSUE TITLE
[PR] 2주차 첫번째 PR 리뷰 반영

### ISSUE THREAD

**Issue by kimyouknow** [kimyouknow/codesquashd-airbnb#19]
## 기능 요청사항

Calendar 컴포넌트를 리팩토링합니다.

## 요청 세부사항

- [x] : 중복되는 로직 함수로 묶어보기
- [x] : 비슷한 타입들 interface와 extends로 중복 줄여보기
- [x] : 매직넘버 줄이기 
- [x] : 배열안의 객체 type 네이밍
- [x] : id 값 객체 -> string이나 number로 수정해보기
- [ ] : js array 고차함수 메서드 map -> filter (의미를 고려해보기)

## 닫는 조건

- 위의 요청 세부사항 해결

**Comment by HongJungKim-dev** [comment]
10시까지 힘냅시다! 확인했습니다~
