### ISSUE TITLE
[Refactor] 캘린더 우측 클릭시 렌더링 리팩토링

### ISSUE THREAD

**Issue by HongJungKim-dev** [kimyouknow/codesquashd-airbnb#29]
## 기능 요청사항

캘린더 우측 클릭시 렌더링 리팩토링

## 요청 세부사항

- [x] 정해진 캘린더 개수 수정
- [x] setTimeout을 대체할 수 있는지 고민하기

## 닫는 조건

- [x] : 다음 만나기 전까지

**Comment by kimyouknow** [comment]
보내주신 pr은 확인하고 merge했습니다!
https://github.com/kimyouknow/codesquad-airbnb/pull/30#issue-1262269295
