### ISSUE TITLE
[Docs] 설계하기

### ISSUE THREAD

**Issue by HongJungKim-dev** [kimyouknow/codesquashd-airbnb#3]
## 기능 요청사항

프로젝트 진행전 전반적인 설계를 진행해봐요

## 요청 요구사항

사용자 흐름, 상태관리, 페어범위, api설계, 컴포넌트 단위 설계, 폴더구조를 작성해봐요

## 닫는 조건

내용이 정리되면 위키에 작성하고 링크를 달아주세요.

**Comment by kimyouknow** [comment]
- [사용자 흐름](https://github.com/kimyouknow/codesquad-airbnb/wiki/%EC%82%AC%EC%9A%A9%EC%9E%90%ED%9D%90%EB%A6%84-%EC%84%A4%EA%B3%84) 
- [설계 방법](https://github.com/kimyouknow/codesquad-airbnb/wiki/%EC%84%A4%EA%B3%84-%EB%B0%A9%EB%B2%95)
- [컴포넌트 단위 설계](https://github.com/kimyouknow/codesquad-airbnb/wiki/%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%8B%A8%EC%9C%84-%EC%84%A4%EA%B3%84)
- [폴더 구조](https://github.com/kimyouknow/codesquad-airbnb/wiki/%ED%8F%B4%EB%8D%94%EA%B5%AC%EC%A1%B0)
- [API 설계](https://github.com/kimyouknow/codesquad-airbnb/wiki/API-%EC%84%A4%EA%B3%84)
