### ISSUE TITLE
[Feat] 가격 범위 차트에 양방향 슬라이더

### ISSUE THREAD

**Issue by HongJungKim-dev** [kimyouknow/codesquashd-airbnb#32]
## 기능 요청사항

양방향 슬라이더

## 요청 세부사항

- [x] : 양방향 슬라이더
- [ ] : x축, y축 라벨 및 헤더, 단위 표시, 평균값표시

## 닫는 조건

- [x] : 오늘 18:00시

**Comment by kimyouknow** [comment]
pr merge해서 닫겠습니다.
